server = 'your server name'
db1 = 'your database name'
uname = 'your service account username'
pword = 'your service account password'
cnxnstr = 'DRIVER={SQL Server};SERVER='+server+';DATABASE='+db1+';UID='+uname+';PWD='+pword+';'
